######################################################################
# Automatically generated by qmake (3.0) Min Des 16 15:33:13 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 18_QTextEdit
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
