######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 18:07:48 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 61_D_SELECT_Data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
