######################################################################
# Automatically generated by qmake (3.0) Rab Jan 9 22:23:17 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 51_QMessageBox
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
