######################################################################
# Automatically generated by qmake (3.0) Sen Jan 14 22:25:15 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 66_B_INSERT_data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
