######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 00:48:55 2019
######################################################################

QT += gui
QT += widgets
QT += core
QT += multimedia

TEMPLATE = app
TARGET = 59_QMediaPlayer_openfile
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
