######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 13:02:13 2019
######################################################################

TEMPLATE = app
TARGET = 37_QQueue
INCLUDEPATH += .

# Input
SOURCES += main.cpp
