######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 23:25:52 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 47_QThread
INCLUDEPATH += .

# Input
HEADERS += mainform.h mythread.h
SOURCES += main.cpp mainform.cpp mythread.cpp
