######################################################################
# Automatically generated by qmake (3.0) Sen Jan 14 22:31:31 2019
######################################################################

QT +=  sql

TEMPLATE = app
TARGET = 66_C_UPDATE_data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
