######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 17:05:45 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 40_QFile_copy
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
