######################################################################
# Automatically generated by qmake (3.0) Sab Des 15 08:23:55 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 14_QLabel_QLineEdit_QPushButton_Calculator
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
