######################################################################
# Automatically generated by qmake (3.0) Sab Des 15 17:57:36 2018
######################################################################

QT += widgets
QT += gui

TEMPLATE = app
TARGET = 16_Gambar_dgn_QPixmap
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
