######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 17:41:27 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 61_A_BUAT_Table
INCLUDEPATH += .

# Input
SOURCES += main.cpp
