######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 21:39:50 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 45_QFileSystemModel
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
