######################################################################
# Automatically generated by qmake (3.0) Rab Jan 9 21:40:41 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 50_Modal_and_Modeless
INCLUDEPATH += .

# Input
HEADERS += dialogform.h mainform.h
SOURCES += dialogform.cpp main.cpp mainform.cpp
