######################################################################
# Automatically generated by qmake (3.0) Min Nov 11 12:32:13 2018
######################################################################

QT += widgets           # baris yang di tambahkan

TEMPLATE = app
TARGET = 01_hellow
INCLUDEPATH += .

# Input
SOURCES += 01_hellow.cpp
