######################################################################
# Automatically generated by qmake (3.0) Jum Jan 4 09:16:42 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 28_QList
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
