######################################################################
# Automatically generated by qmake (3.0) Sel Jan 8 00:07:55 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 49_QDialog_TambahData
INCLUDEPATH += .

# Input
HEADERS += dialogform.h mainform.h
SOURCES += dialogform.cpp main.cpp mainform.cpp
