######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 17:21:02 2019
######################################################################

QT += widgets
QT += core

TEMPLATE = app
TARGET = 41_QFile_rename
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
