######################################################################
# Automatically generated by qmake (3.0) Kam Jan 10 21:37:50 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 56_QColorDialog
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
