######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 19:19:10 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 63_A_INSERT_Data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
