######################################################################
# Automatically generated by qmake (3.0) Jum Jan 4 21:17:53 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 29_QProgressBar
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
