######################################################################
# Automatically generated by qmake (3.0) Min Nov 11 19:16:08 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 05_QDesktopWidget
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
