######################################################################
# Automatically generated by qmake (3.0) Min Nov 11 23:21:13 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 06_MultiForm
INCLUDEPATH += .

# Input
HEADERS += mainform.h otherform.h
SOURCES += main.cpp mainform.cpp otherform.cpp
