######################################################################
# Automatically generated by qmake (3.0) Jum Jan 11 23:32:10 2019
######################################################################

QT += core
QT += gui
QT += widgets
QT += multimedia

TEMPLATE = app
TARGET = 58_QMediaPlayer
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
