######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 14:00:01 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 38_QFile
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
