######################################################################
# Automatically generated by qmake (3.0) Min Des 16 16:54:05 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 19_QRadioButton_Calculator
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
