######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 19:42:18 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 43_QDir
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
