######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 21:26:41 2019
######################################################################

QT += gui
QT += core
QT += widgets
QT += sql

TEMPLATE = app
TARGET = 64_Phonebook_Manager
INCLUDEPATH += .

# Input
HEADERS += entryform.h mainform.h
SOURCES += entryform.cpp main.cpp mainform.cpp
