######################################################################
# Automatically generated by qmake (3.0) Min Des 16 19:17:56 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 23_QFontComboBox
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
