######################################################################
# Automatically generated by qmake (3.0) Kam Jan 10 00:40:43 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 54_QFileDialog_getExistingDirectory
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
