######################################################################
# Automatically generated by qmake (3.0) Kam Des 13 23:12:11 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 10_QGridLayout
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
