######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 17:53:42 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 61_B_MANIPULASI_Data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
