######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 12:54:49 2019
######################################################################

TEMPLATE = app
TARGET = 36_QStack
INCLUDEPATH += .

# Input
SOURCES += main.cpp
