######################################################################
# Automatically generated by qmake (3.0) Rab Jan 9 23:07:16 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 52_QFileDialog
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
