######################################################################
# Automatically generated by qmake (3.0) Jum Des 14 21:51:37 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 13_Phonebook_Manager_example
INCLUDEPATH += .

# Input
HEADERS += entryform.h mainform.h
SOURCES += entryform.cpp main.cpp mainform.cpp
