######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 23:16:11 2019
######################################################################

QT += gui
QT += core
QT += widgets
QT += sql

TEMPLATE = app
TARGET = 65_QSqlTableModel
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
