######################################################################
# Automatically generated by qmake (3.0) Jum Jan 11 21:31:28 2019
######################################################################

QT += gui
QT += core
QT += widgets

TEMPLATE = app
TARGET = 57_CreateTextEditor
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
