######################################################################
# Automatically generated by qmake (3.0) Sab Jan 5 20:30:23 2019
######################################################################

TEMPLATE = app
TARGET = 33_1_QStringHello
INCLUDEPATH += .

# Input
SOURCES += main.cpp
