######################################################################
# Automatically generated by qmake (3.0) Min Nov 11 13:52:03 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 02_hello1
INCLUDEPATH += .

# Input
HEADERS += MinimalForm.h
SOURCES += main.cpp MinimalForm.cpp
