######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 19:13:27 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 62_B_SELECT_Data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
