######################################################################
# Automatically generated by qmake (3.0) Sen Jan 14 22:12:49 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 66_A_Connection
INCLUDEPATH += .

# Input
SOURCES += main.cpp
