######################################################################
# Automatically generated by qmake (3.0) Min Nov 11 14:24:43 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 03_tambahtagHTML
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
