######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 17:46:43 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 42_QFile_remove
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
