######################################################################
# Automatically generated by qmake (3.0) Kam Jan 10 21:19:54 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 55_QFontDialog
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
