######################################################################
# Automatically generated by qmake (3.0) Jum Jan 4 23:55:49 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 32_QTableWidget
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
