######################################################################
# Automatically generated by qmake (3.0) Min Nov 11 18:38:58 2018
######################################################################

QT += widgets       # tambahan, untuk QWidget

TEMPLATE = app
TARGET = 04_ClosewithButton
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
