######################################################################
# Automatically generated by qmake (3.0) Sel Jan 15 21:28:35 2019
######################################################################

QT += gui
QT += core
QT += widgets
QT += sql

TEMPLATE = app
TARGET = 67_Latihan_SQL_Executor
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
