######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 10:37:07 2019
######################################################################

TEMPLATE = app
TARGET = 34_QStringList
INCLUDEPATH += .

# Input
SOURCES += main.cpp
