######################################################################
# Automatically generated by qmake (3.0) Min Des 16 22:05:33 2018
######################################################################

QT += widgets
QT += core

TEMPLATE = app
TARGET = 25_QDateEdit_QTimeEdit_QDateTimeEdit
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
