######################################################################
# Automatically generated by qmake (3.0) Sen Jan 14 22:36:00 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 66_D_DELETE_data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
