######################################################################
# Automatically generated by qmake (3.0) Min Des 16 16:46:00 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 22_QComboBox
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
