######################################################################
# Automatically generated by qmake (3.0) Sen Jan 14 22:40:58 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 66_E_SELECT_data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
