######################################################################
# Automatically generated by qmake (3.0) Jum Jan 4 22:48:40 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 31_QTreeWidget_with_Header
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
