######################################################################
# Automatically generated by qmake (3.0) Jum Jan 4 22:00:56 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 30_QTreeWidget
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
