######################################################################
# Automatically generated by qmake (3.0) Sen Jan 7 23:05:18 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 48_QDialog
INCLUDEPATH += .

# Input
HEADERS += dialogform.h mainform.h
SOURCES += dialogform.cpp main.cpp mainform.cpp
