######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 19:21:26 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 63_B_SELECT_Data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
