######################################################################
# Automatically generated by qmake (3.0) Min Des 16 21:54:58 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 20_QCheckBox
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
