######################################################################
# Automatically generated by qmake (3.0) Kam Des 13 22:15:49 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 08_QVBoxLayout
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
