######################################################################
# Automatically generated by qmake (3.0) Kam Des 13 23:47:23 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 11_Label_dan_GridLayout
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
