######################################################################
# Automatically generated by qmake (3.0) Sab Des 15 08:52:06 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 15_Show_Gambar_dengan_QLabel
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
