######################################################################
# Automatically generated by qmake (3.0) Sab Jan 5 20:45:17 2019
######################################################################

TEMPLATE = app
TARGET = 33_2_AddString
INCLUDEPATH += .

# Input
SOURCES += main.cpp
