######################################################################
# Automatically generated by qmake (3.0) Sen Nov 12 00:40:14 2018
######################################################################

QT += widgets
QT += gui

TEMPLATE = app
TARGET = 07_Tooltip-MouseHover
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
