######################################################################
# Automatically generated by qmake (3.0) Min Des 16 15:00:11 2018
######################################################################

QT += widgets
QT += gui

TEMPLATE = app
TARGET = 17_Tombol_diKasih_Icon
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
