######################################################################
# Automatically generated by qmake (3.0) Kam Jan 3 22:37:41 2019
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 27_QSlider_QLCDNumber
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
