######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 18:04:21 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 61_C_INSERT_Data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
