######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 11:57:44 2019
######################################################################

TEMPLATE = app
TARGET = 35_QList
INCLUDEPATH += .

# Input
SOURCES += main.cpp
