######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 19:11:42 2019
######################################################################

QT += sql

TEMPLATE = app
TARGET = 62_A_INSERT_Data
INCLUDEPATH += .

# Input
SOURCES += main.cpp
