######################################################################
# Automatically generated by qmake (3.0) Jum Des 14 08:33:21 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 12_SIGNAL_SLOT_Clear_LineEdit
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
