######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 22:04:53 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 46_QTimer
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
