######################################################################
# Automatically generated by qmake (3.0) Sab Jan 12 16:27:56 2019
######################################################################

QT += gui
QT += core
QT += widgets
QT += multimedia
QT += multimediawidgets

TEMPLATE = app
TARGET = 60_QVideoWidget
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
