######################################################################
# Automatically generated by qmake (3.0) Kam Jan 3 21:53:59 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 26_QCalendar
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
