######################################################################
# Automatically generated by qmake (3.0) Min Des 16 20:08:52 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 24_QSpinBox
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
