######################################################################
# Automatically generated by qmake (3.0) Min Des 16 23:05:12 2018
######################################################################

QT += widgets

TEMPLATE = app
TARGET = 21_QCheckBox_Flag_atau_Status
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
