######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 14:38:37 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 39_QTextStream
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
