######################################################################
# Automatically generated by qmake (3.0) Min Jan 6 20:15:55 2019
######################################################################

QT += core
QT += widgets

TEMPLATE = app
TARGET = 44_QDirModel
INCLUDEPATH += .

# Input
HEADERS += mainform.h
SOURCES += main.cpp mainform.cpp
